### ISSUE TITLE
Publish as a Note - abandoned work item?

### ISSUE THREAD

**Issue by chaals** [w3c/XMLHttpRequest#2]
There is no current plan to finish this work. We propose at this time to publish it as a W3C Note indicating that work has stopped on a formal "version 1" specification.

Feel free to add a +1 - or -1 if you disagree.

Note that without a concrete proposal to do the actual work required, nothing will happen...

**Comment by rebecaruiz** [comment]
+1

**Comment by ZoeBijl** [comment]
+1

**Comment by dontcallmedom** [comment]
the note has been published, the issue can be closed https://www.w3.org/TR/XMLHttpRequest/

**Comment by chaals** [comment]
Thanks Dom.

**Comment by jungkees** [comment]
Thanks for having taken care of this.
